### ISSUE TITLE
Slackにテスト結果を通知して欲しい

### ISSUE THREAD

**Issue by mwakizaka** [Magic-Pod/japanese-issue-and-doc#137]
CircleCIやBitriseと連携していれば、そこから通知をもらうことも可能だが、Magic-Pod でもできると嬉しい

**Comment by NozomiIto** [comment]
https://slack.com/intl/ja-jp/help/articles/206819278-Slack-%E3%81%AB%E3%83%A1%E3%83%BC%E3%83%AB%E3%82%92%E9%80%81%E4%BF%A1%E3%81%99%E3%82%8B このあたりの方法が現状の回避策と思われます。

**Comment by NozomiIto** [comment]
https://twitter.com/ogniriak/status/1482016399031947268

**Comment by NozomiIto** [comment]
0.99.0で対応

**Comment by NozomiIto** [comment]
0.99.1で対応(ローカルPCテストを除く)
