### ISSUE TITLE
クラウド端末で端末/バージョンを選びたい

### ISSUE THREAD

**Issue by mwakizaka** [Magic-Pod/japanese-issue-and-doc#139]
現状 iPhone 8(iOS13.1) / Nexus 5X(Android 10) しか選べないが、他機種、他バージョンを指定したい

**Comment by NozomiIto** [comment]
0.55.0で
iOS11,12,13
Android5,6,7,8,9,10
のシミュレータ・エミュレータ各機種対応完了
