### ISSUE TITLE
共有UIやステップが「プロジェクト」を跨いで使えるようにしてほしい

### ISSUE THREAD

**Issue by ghost** [Magic-Pod/japanese-issue-and-doc#154]
要望としてはtitleのとおりです。

1つのアプリ内に多くの複数のサービス/機能がある場合、総テスト数が膨大になります。
現状テストの一括実行がプロジェクトごとのため、その実行に長大な時間がかかると想像してます。
また、テストケース数が多いと視認性なども下がりメンテナンス性を損なうことも想像してます。

・プロジェクトを分けると
　→共通UIやステップを都度都度作成する必要があり大変になる。

・プロジェクトを分けないと
　→一括実行が終わらなくなる、（おそらく）メンテナンス性が下がる

共通UIやステップをプロジェクトが跨いで使えるか、あるいはプロジェクトで以下の点を改善ご検討いただけますと助かります。

・UIが多すぎて整理しにくい
・テストが多すぎて整理しにくい
・テスト時間が長くなりすぎて困る
（テストの一括実行をプロジェクト単位でないようにするなど）

**Comment by NozomiIto** [comment]
1アプリ1プロジェクトの構成を想定して開発をしているので、この構成で使いにくい部分を改善したいと思っています。

> ・UIが多すぎて整理しにくい

こちらはセクション分割などの機能はある程度用意されていますが、もっと使いやすくする、重複しているUIを自動でまとめてくれる機能などを改善していきたいと思っています。(https://github.com/Magic-Pod/japanese-issue-and-doc/issues/149)

> ・テストが多すぎて整理しにくい

こちらはテストをフォルダ整理、カテゴリ分割できるなどの機能をつけて改善したいと思います。

> テスト時間が長くなりすぎて困る

こちらは、テスト番号を指定してテスト実行する、ラベルを指定してテスト実行する、などの方法でテストが長くならないようにできると思います。

**Comment by NozomiIto** [comment]
#149, #439 があるのでクローズ
