### ISSUE TITLE
共有ステップを別の共有ステップから呼び出したい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#160]

**Comment by HitoshiSuguro** [comment]
複数の共有ステップ実行をまとめて新しいステップを定義する機能があると助かります。

**Comment by NozomiIto** [comment]
かしこまりました！
暫定回避策として、共有ステップ編集画面でステップの内容を右クリックしてコピーし、別の共有ステップの編集画面に貼り付けすることで、ある共有ステップの内容を別の共有ステップに持っていくことができます。

**Comment by HitoshiSuguro** [comment]
なるほど。コピペで進めればやりたいこととしては、実現出来そうです！
共有ありがとうございます！

**Comment by gkzz** [comment]
> 共有ステップを別の共有ステップから呼び出したい

前処理や後処理といったほんとうにやりたいこと以外の処理を別々の共有ステップとして定義しておき、呼び出し元ではほんとうにやりたいことでネーミングされた共有ステップを呼ぶようにすれば、複雑な処理がシンプルに書けるのでは、、！と思ったのでスタンプを押しました！！


ログイン処理の前処理をまとめた

**Comment by nkns165** [comment]
0.99.40にて共有ステップの3階層までの入れ子に対応しました。
ですが、まだ少し制約事項がありまして

> 複数の共有ステップ実行をまとめて新しいステップを定義する機能

こちらを実現するには少し手間がかかる状況です（新規共有ステップを作ったあとで、そこに必要な既存の共有ステップを追加する必要がある）。
さらに利便性を上げるため、
・共有ステップを作成するときに既存の共有ステップ実行を含められるようにする
・親から子へ共有ステップの変数の値を受け渡せるようにする
という変更を直近で取り組んでいます。特に2点目について、現状の仕様での対応策も[ヘルプページ](https://support.magic-pod.com/hc/ja/articles/22615983082521)に記載しておりますが、変数の値の受け渡しを多用されたい場合は機能改修をお待ちいただく方が良いかもしれません。

**Comment by Mamitsubute** [comment]
上記コメントにあります
> ・親から子へ共有ステップの変数の値を受け渡せるようにする

については[バージョン1.6.0](https://support.magic-pod.com/hc/ja/articles/28144039190169)にて対応いたしました。

**Comment by nkns165** [comment]
お知らせが漏れており大変申し訳ありません。

> ・共有ステップを作成するときに既存の共有ステップ実行を含められるようにする

こちらにつきましても[バージョン1.0.0](https://support.magic-pod.com/hc/ja/articles/24604617254937-%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B31-0-0-2023-10-30)で対応済みです。
上で書いていた残件が2つとも完了しましたので、こちらの課題はクローズいたします。
