### ISSUE TITLE
失敗時に処理を継続するかをコマンドごとに選べるように

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#190]
「失敗したらその場でエラー」「失敗しても最後まで続けてあとでまとめてエラー」「失敗しても無視」のいずれかを各コマンドで指定できるように。値チェックや待ち処理など、失敗しても続けてもいいケース、最後にまとめてエラーになればいいケースはある。
また、値を選択すると選択内容に応じた処理が行われるが値は元に戻ってしまうプルダウンなども、失敗しても続けたいパターン。

**Comment by nkns165** [comment]
0.99.27にて部分的に対応済み。
各「確認」コマンドにて、失敗時の挙動を「失敗時点でテスト終了」「失敗扱いとしてテストを継続」（上の「失敗したらその場でエラー」「失敗しても最後まで続けてあとでまとめてエラー」に相当）を選択できるようになりました。
「失敗しても無視」については確認コマンドでは必要ないはずなのでサポート外で、今後別コマンドに適用する際に考慮に入れます。

**Comment by NozomiIto** [comment]
- 確認以外でコマンドのあらゆる失敗を無視したい具体的ケースは少ない。( https://github.com/Magic-Pod/japanese-issue-and-doc/issues/243 など限られる)
- 待機に失敗しても継続したいという声もあるが、待機の結果で分岐したいなど、もう少し違うことがしたいことが多い

各コマンドに「失敗しても無視」をつけるのは不適当なので、このIssueはクローズ
