### ISSUE TITLE
スワイプ設定画面の改善

### ISSUE THREAD

**Issue by yo-yoneyama** [Magic-Pod/japanese-issue-and-doc#224]
<img width="327" alt="スクリーンショット 2020-09-30 13 01 00" src="https://user-images.githubusercontent.com/10388255/94641780-24b97180-031d-11eb-96ad-0b81d196853e.png">

1. (Issue) **"方向"** の値に `0` をセットしたい場合に `0` と入力しても反映されず、入力前の値に戻ってしまうため、毎回手動で調整する必要がある（その他の値については0もセットできる）。

2. (要望) X/Yの座標の初期値が0/0%だが、実際には左上ではなく、中央から指定した方向へスワイプしたいケースが一般的のため、毎回変更している。そのため、初期値を 50/50% にして頂けると助かります。

**Comment by NozomiIto** [comment]
0.70.0で対応しました。( 1. 2. 両方とも)
