### ISSUE TITLE
Flutterアプリのサポート

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#242]
- https://forum.katalon.com/t/need-a-solution-to-send-text-on-text-box-of-flutter-app/42836/5
- appium-flutter-driverなどの利用が必要な模様

**Comment by NozomiIto** [comment]
- https://flutter.dev/showcase
- https://www.e-xtreme.co.jp/topics/9765/

結構使っているアプリも増えてきたのかも

**Comment by NozomiIto** [comment]
すでに問い合わせ3社目につき https://github.com/Magic-Pod/japanese-issue-and-doc/blob/master/UPCOMING_FEATURES.md の開発予定に追加

**Comment by NozomiIto** [comment]
https://blog.bitrise.io/state-of-app-development-2020

**Comment by mwakizaka** [comment]
2023/07/31よりモバイルのFlutterアプリサポートを開始しました！
詳しくはhttps://magicpod.com/resources/flutter_guide/ をご覧ください
