### ISSUE TITLE
共有ステップのコピー機能が欲しい

### ISSUE THREAD

**Issue by ryohirose-Fukuoka** [Magic-Pod/japanese-issue-and-doc#251]
［要望の背景］
Release予定のVersion2.00と、ユーザーに現在提供されてるVersion1.92のアプリがあると仮定します。
・Version2.00もTest対象ですし、ユーザーに影響のあるVersion1.92でこちらもTestする必要があります。
・Version2.00と、Version1.92ではLocatorが大きく異なります。

TestをVersion1.92でもVersion2.00でも行いたい場合、共有ステップをVersion1.92用とVersion2.00用に作成したいです。
条件分岐が現状コピペできなないため、1から作成し直すか、共有ステップ内で○○が存在しない場合、という条件分岐で対応してます。

前者は工数が大きくかかり、後者は可読性が悪くなり複雑なのでミスのもとになります。

共有ステップのコピー機能があれば嬉しいので、ご検討のほど宜しくお願いします。

**Comment by NozomiIto** [comment]
https://github.com/Magic-Pod/japanese-issue-and-doc/issues/231 と同じ内容ですね！比較的直近のスケジュールに入っております。

**Comment by ryohirose-Fukuoka** [comment]
あ、ありがとうございます！
重複失礼致しました＞＜

**Comment by NozomiIto** [comment]
0.69.0で対応しました！
