### ISSUE TITLE
テスト一括実行において、データパターンの一部のパターンだけを実行したい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#260]
テストケース番号のところで、`1[1],1[2]` のような形でテスト番号 + データパターン番号を指定できるのがよさそう。

**Comment by nkns165** [comment]
0.99.32にて対応しました。現状、パターン番号を1つずつ括弧で囲んで`1[1],1[2]` のような形でパターンを指定できます。
