### ISSUE TITLE
ブラウザテストでマイク・カメラの使用を許可したい

### ISSUE THREAD

**Issue by yo-yoneyama** [Magic-Pod/japanese-issue-and-doc#280]
<img width="324" alt="スクリーンショット 2021-02-17 11 19 16" src="https://user-images.githubusercontent.com/10388255/108147419-28a23080-7112-11eb-93ea-f24b51213cf2.png">

上記のモーダルがキャプチャに含まれないため、許可することが出来ない。
（且つ裏のウィンドウから位置指定のクリックも難しい..）

モーダルからの許可でなく、予め設定上で許可しておくでも問題ありませんので、許可した状態でテストを実行できる方法があると助かります。

**Comment by NozomiIto** [comment]
0.84.0で修正
