### ISSUE TITLE
テスト一括実行画面と作成画面でテスト実行設定を共有したい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#281]
共有変数などを、テストごとに設定 & テスト一括実行設定でも設定するのは面倒

**Comment by yo-yoneyama** [comment]
関連して、
一部の設定だけ変更した別の設定を用意したいケースがあるのですが、現状だと新規で設定を作る事になるため
設定内容をコピーから作成することも出来るようになると助かります！

**Comment by NozomiIto** [comment]
コピー機能は0.99.3でリリース

**Comment by NozomiIto** [comment]
0.99.5で対応
