### ISSUE TITLE
ブラウザ上で時間がかかる操作が完了したときにプッシュ通知して欲しい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#296]
- ブラウザのプッシュ通知。ブラウザタブの色を変えるでは気づかない
- ブラウザウィンドウやタブがアクティブじゃない状態で、テストが完了したとき(特にバッチテスト)。テスト成功失敗がわかるとよい
- ブラウザウィンドウやタブがアクティブじゃない状態で、クラウド端末がシステムにより切られようとしている時
- ブラウザウィンドウやタブがアクティブじゃない状態で、クラウド端末が起動した時(デフォルトでないクラウド端末だと時間がかかるので)

テスト編集画面で端末を最初立ち上げるまでやテスト実行ボタンを押した後完了まで時間がかかるので、その間他のことをしていると、
気づかず時間が経ってクラウド端末が時間切れで終了している。そもそも10分の時間切れがシビアすぎるという話でもある。

**Comment by nkns165** [comment]
0.99.27で対応
