### ISSUE TITLE
今日が月末かを判定したい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#337]
日付計算コマンドの「日付種別」で「月末」が選べれば、今月末、来月末などが取得できる。そうすれば、あとは条件分岐コマンドと変数を使って今日の日が月末か判定できるはず。

なお、初月末月は1月か12月かで判定すればいいし、月初の日かは1日かで判定すればいい。月末だけが専用の処理がないとうまくいかない。

**Comment by mwakizaka** [comment]
0.85.0で対応
