### ISSUE TITLE
magic_pod_configの設定の中で、環境変数が展開されるものとされないものがある

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#370]
- ローカルPCテストの場合、全部展開されて問題ないはず。
- 共有変数 -> envVarsの値(ローカルPCテストの場合のみ) -> 外側から指定された値(ローカルPCテストの場合のみ)、の優先順位で利用すれば良さそうだが。 -> 逆かも。要検討

workDirについては、昔は${HOME}など環境変数が使えたはずだが ( https://www.trident-qa.com/magic-pod-variable/ )、最近は `Relative workDir is not permitted:` が出てしまう模様。。

**Comment by NozomiIto** [comment]
0.99.0で対応

**Comment by nkns165** [comment]
次回リリースで対応予定

**Comment by NozomiIto** [comment]
0.99.1で対応
