### ISSUE TITLE
iOSの要素のテキストをテキスト取得コマンドで取ると、LF改行が半角スペースになっている

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#372]
- Appium/XCUITestの仕様かもしれない。
- https://github.com/Magic-Pod/japanese-issue-and-doc/issues/109 で改善を入れたが完全に直っていない

**Comment by NozomiIto** [comment]
一方Magic Podが生成するLocatorは改行を含むものになっているが、要素を特定するにはそれではうまくいかず改行を半角スペースに置き換えないとダメな模様。。UIツリー上ではLF改行は「&#10;」で表現されている。

**Comment by NozomiIto** [comment]
0.90.0で再対応

**Comment by nkns165** [comment]
制限事項については以下をご参照ください。
https://support.magic-pod.com/hc/articles/4409262184217
