### ISSUE TITLE
画面キャプチャ一括ダウンロードが遅い

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#401]
- 画面からダウンロードの場合、画面が固まってしまうので、非同期で実施して終わったら通知すべき
- APIからダウンロードの場合も何か非同期なAPIに変えた方が良さそう。普段はmagic-pod-api-clientでダウンロードすれば、利用者は複雑な待機ロジックを書く必要もない

**Comment by NozomiIto** [comment]
0.94.0で画面は固まらないように

**Comment by mwakizaka** [comment]
- バージョン0.94.0で解決済み (https://support.magic-pod.com/hc/ja/articles/4414260152217-%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B30-94-0-2022-1-9-)
- なお、magicpod-api-clientは0.95.0.1への更新が必要(https://github.com/Magic-Pod/magicpod-api-client/releases/tag/0.95.0.1)
