### ISSUE TITLE
共有ステップを作る際に、共有UIにすべきUIがあれば一緒に共有にするか確認してほしい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#419]
- 別途共有にする必要があるのは面倒
- 裏で何も言わずに勝手に共有にするのは、好ましく無いと思われる

**Comment by nkns165** [comment]
1.3.0にて対応しました。
共有ステップを作成する際、共有化されていないUIがある場合には確認ダイアログが表示され、一括で共有化することができます。
