### ISSUE TITLE
テストケース一覧に作成者も表示してほしい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#426]
・自分が作成したものが一覧の中でわかりやすいとよい

**Comment by NozomiIto** [comment]
表示オプションの選択肢に追加すればよい。

![Screen Shot 2022-11-10 at 14 43 30](https://user-images.githubusercontent.com/4276719/201010095-2760c2ba-bab4-4209-9c23-8fda335b6998.png)

**Comment by NozomiIto** [comment]
あと最終更新日時も

**Comment by nkns165** [comment]
0.99.33にて、以下の情報を追加しました。
- 作成者
- 作成日時
- 最終更新者
- 最終更新日時
- 画像差分ステップ数
