### ISSUE TITLE
テスト結果のメール通知を管理者もしくは所有者が設定できるようにしたい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#434]
「テスト結果をメール通知ON」にユーザーが気付かず実行して通知がたくさん届いてしまうことがある

**Comment by MtDeity** [comment]
またはデフォルトをOFFに設定できるようにする

**Comment by NozomiIto** [comment]
https://github.com/Magic-Pod/japanese-issue-and-doc/issues/443 で対応
