### ISSUE TITLE
モバイルアプリでスクロール途中の画面に対し画像差分チェックをしたい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#442]
- 普通だと、スクロールするたびに位置がずれているので、毎回差分が発生してしまう。
- 上から下まで一度スクロールして縦長の正解画像を用意し、テスト実行時にはその正解のどこかの箇所と一致するかチェック、みたいなやり方なら、実現はできそう。

**Comment by nkns165** [comment]
> 普通だと、スクロールするたびに位置がずれているので、毎回差分が発生してしまう。

1.2.0にてAndroidのスワイプ距離が一定になるような改修を入れました。画像差分チェックの機能は特に改修していませんが、これによりスワイプ後の画面についても画像差分チェックが使えるようになります。

iOSについても同様に改修を進めており、今後リリース予定です。

**Comment by nkns165** [comment]
1.4.0にてiOSについても改修をリリースしましたので、このissueはクローズします。
