### ISSUE TITLE
テスト失敗時にリトライ前の実行キャプチャも確認したい

### ISSUE THREAD

**Issue by yo-yoneyama** [Magic-Pod/japanese-issue-and-doc#463]
自動リトライがONの場合、リトライ前とリトライ後でエラー原因が変わるケースが多く、リトライ前の実行結果（キャプチャ）も参照したい。

※ テストの問題でもあるが、リトライ時にはデータや状態の違いからリトライ前とは別要因で落ちているケースが多く、本来の失敗原因を探るには実行ログから調査 or 再実行を行う必要があるため

**Comment by NozomiIto** [comment]
https://github.com/Magic-Pod/japanese-issue-and-doc/issues/240 と同じ内容なのでそちらに統合
