### ISSUE TITLE
BrowserStackやSauceLabsでTestFlightからアプリをインストールするテストを自動化したい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#472]

**Comment by rihokokabo** [comment]
現状でも「別アプリ起動」コマンドでBrowserStackで初期インストールされているTestFlightのバンドルIDを起動すれば一応できるが、あまりきれいではない。

**Comment by rihokokabo** [comment]
iOSのバグでAppStoreやTestFlight版でのみクラッシュが起こるということが発生しており、それをテストで防ぎたい

**Comment by NozomiIto** [comment]
- BrowserStackではapp IDを指定してのテストは対応されていない。また、App Automateの際にはTestFlightは端末にインストールされていない。
- SauceLabsでは自動テスト用端末にTestFlightやAppStoreはインストールされていない。(インストールされているSafariやカレンダーなどはバンドルIDを指定して起動ができるよう)

ということで、残念ながら対応は難しい。
