### ISSUE TITLE
テストケースの説明欄にURLを記載した場合、リンクになって欲しい

### ISSUE THREAD

**Issue by yo-yoneyama** [Magic-Pod/japanese-issue-and-doc#477]
テストケースのオーバービューに、コンフルやGithubなど他サイトのリンクを貼った場合に現状だとリンクにならずURL直書きになってしまう。
URLが長いとオーバービューも見辛いため、代替テキストに対してリンクを貼れると嬉しいですが、URLの場合リンクになっている (クリックで飛べる) だけでも有り難いです。

**Comment by NozomiIto** [comment]
0.99.16で対応

**Comment by yo-yoneyama** [comment]
ありがとうございます!! 便利になりました。
