### ISSUE TITLE
"Android Environment Check" failed

### ISSUE THREAD

**Issue by yamatakau08** [Magic-Pod/japanese-issue-and-doc#48]
Mac OS High Sierra version 10.13.2 の環境です。
Tool → Android Environment Check を実行すると、下記のダイアログが表示されます。

<img width="1020" alt="2018-02-15 13 54 21" src="https://user-images.githubusercontent.com/13044987/36241254-74a8b66e-1258-11e8-9d34-f8da3cd7a752.png">

appium-uiautomator2-server-v1.1.0.apk 存在するのですが、file sizeが 0byteです。
下記のイメージ図になります。

インストール/展開時に失敗しているのでしょうか？
このファイルどこから個別に入手可能でしょうか？
対処方法ご教示いただけますか？

<img width="687" alt="2018-02-15 13 57 31" src="https://user-images.githubusercontent.com/13044987/36241255-7750e92c-1258-11e8-8df1-f945c6e01c09.png">

**Comment by yamatakau08** [comment]
Version 0.14.0 です。
<img width="287" alt="2018-02-15 15 26 55" src="https://user-images.githubusercontent.com/13044987/36243433-da7efec4-1264-11e8-8e6f-a3cd739f1151.png">

```
sqanoMacBook-Pro:apks sqa$ java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
Java8 に戻す。
Magic Pod Desktop Uninstall → Install
した方が良いでしょうか？

できれば、一度 v1.1.0 apk のみを入れて確認したいのですが、
[https://github.com/appium/appium-uiautomator2-server/releases/tag/v1.1.0](url)
には、v1.1.0 apk ありませんでした。

Magic Pod Destkopは、アプリケーションフォルダに入れてます。
<img width="425" alt="2018-02-15 15 27 19" src="https://user-images.githubusercontent.com/13044987/36243439-ddfffeae-1264-11e8-80f8-3ed75b65c52b.png">

**Comment by NozomiIto** [comment]
[appium-uiautomator2-server-v1.1.0.apk.zip](https://github.com/Magic-Pod/japanese-issue-and-doc/files/1726676/appium-uiautomator2-server-v1.1.0.apk.zip)

こちらがappium-uiautomator2-server-v1.1.0.apkですが、Magic Podの問題の場合、置き換えてもまた0byteに戻ってしまう気がします。

Magic Podの問題の場合、「Java8 に戻す & Magic Pod Desktop Uninstall → Install」で暫定的に問題を回避できる可能性が高いです。

Java9まわりの問題は修正したはずだったのですが、まだ残存しているのかもしれません。。あとで調べてみます。

すみませんが、よろしくお願いします。

**Comment by yamatakau08** [comment]
> 「Java8 に戻す & Magic Pod Desktop Uninstall → Install」で暫定的に問題を回避できる可能性が高いです。

ご教示いただいた対応方法で、Tool → Android Environment Check 実行結果が
"Check succeeded!" 
のダイアログが表示され、正常になりました。

**Comment by NozomiIto** [comment]
Java9まわりの問題が残っていたので、バージョン0.16.0で修正しました。
