### ISSUE TITLE
部分実行で範囲を選択する際もステップ番号がわかるようにしてほしい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#482]
部分実行をする際にステップ番号を参照して選択したい

**Comment by ReiAkimoto** [comment]
部分実行選択範囲を下から上へ選択できるようにしてほしいが、とりあえずステップ番号があるだけでも助かる

**Comment by NozomiIto** [comment]
> 部分実行をする際にステップ番号を参照して選択したい

0.99.14で対応
