### ISSUE TITLE
テスト結果に失敗原因などをユーザが入力できる欄がほしい

### ISSUE THREAD

**Issue by ReiAkimoto** [Magic-Pod/japanese-issue-and-doc#488]
現状ユーザで失敗原因などを管理しているが、MagicPod上でできると効率的

**Comment by nkns165** [comment]
1.5.0にて対応しました。各テスト結果に対して「メモ」を追加できるようになっており、テスト結果の一覧画面や一括実行結果の詳細画面でも確認ができます。
