### ISSUE TITLE
Spotify Appのテスト実行で、Spotify App終了してしまう

### ISSUE THREAD

**Issue by yamatakau08** [Magic-Pod/japanese-issue-and-doc#49]
macOS High Sierra バージョン 10.13.2
Android端末 Xperia Z3 Androidバージョン 5.02
Magic Pod Desktop バージョン 0.14.0

の環境で、

Spotify Appの自動テスト実行を行なっているのですが...

Chrome Browserより、Magic Podにて、テスト実行を行うと、

[端末側] 
Appium Settingsが起動後、しばらくして、Spotify App起動。
「次へ」アイコン　タップが実行されず？に、Spotify App終了。
<img width="459" alt="2018-02-19 13 27 29" src="https://user-images.githubusercontent.com/13044987/36362508-d35daf48-1578-11e8-9179-9dd188322fbf.png">
<img width="456" alt="2018-02-19 13 28 13" src="https://user-images.githubusercontent.com/13044987/36362510-d7378300-1578-11e8-95d9-6722aee1a6ba.png">

[[Browser側]] 成功
<img width="903" alt="2018-02-19 13 25 10" src="https://user-images.githubusercontent.com/13044987/36362460-609b7ce2-1578-11e8-85da-078d00d50229.png">
[console log]
```
platform: Android UiAutomator2
[1] tap(「次へ」アイコン)
    ✓ run (4701ms)


  1 passing (26s)

test succeeded
```
[appium console log]
[appium_gui.log](https://github.com/Magic-Pod/japanese-issue-and-doc/files/1735556/appium_gui.log)

端末側は、Spotify App終了せずに、そのまま起動を続け、フォアグラウンド状態
を保つ気がしていたのですが...、なぜ終了するのでしょうか？

何をどのように解析して行けば良いか、ご教示いただけますでしょうか？

**Comment by NozomiIto** [comment]
- Magic Podでは、テストごとにアプリを自動的に起動・終了するようになっています。なので、テスト後にSpotify Appが終了されております。
- 「次へ」アイコンはおそらくタップされたのだと思いますが、アプリが直後に終了しているため目視が難しくなっているのだと思います。試しに「待機」>「秒間待つ」のコマンドなどを入れてみると、タップされている様子が目でわかるのではないかと思います。

https://github.com/Magic-Pod/japanese-issue-and-doc/issues/50 に今後の改善として起票しておきました。

**Comment by yamatakau08** [comment]
NozomiItoさん、
ご回答ありがとうございます。

> Magic Podでは、テストごとにアプリを自動的に起動・終了するようになっています。

理解しました。

**Comment by yamatakau08** [comment]
> 「次へ」アイコンはおそらくタップされたのだと思いますが、アプリが直後に終了しているため目視が難しくなっているのだと思います。試しに「待機」>「秒間待つ」のコマンドなどを入れてみると、タップされている様子が目でわかるのではないかと思います。

<img width="950" alt="2018-02-19 15 29 33" src="https://user-images.githubusercontent.com/13044987/36364982-ae3dd500-158a-11e8-964d-69f4755afe4a.png">

ご教示いただいた、「秒間待つ」を、入れてみましたが...
"Daily Mix1" や "次へ「アイコン」"が 押されず、終了しています。

端末側画面動画をキャプチャしたものを、zip ファイルにて添付します。
ご教示お願いします。
[Spotify on magic pod 02.mp4.zip](https://github.com/Magic-Pod/japanese-issue-and-doc/files/1735756/Spotify.on.magic.pod.02.mp4.zip)

**Comment by NozomiIto** [comment]
http://www.trident-qa.com/magic-pod-developer-troubleshooting/#sec1_1 の方法で、各要素に対応するシステム情報がどうなっているかを確認できます。
"Daily Mix1" や "次へ「アイコン」"のシステム情報はどうなっているでしょうか。

**Comment by yamatakau08** [comment]
システム情報を添付します。
お手数をおかけしますが、アドバイスお願いします。

[Dail Mix1]
<div class="ocr-text" data-text="Daily Mix1" data-id="83" data-component="ocr_text" data-x="189" data-y="951" data-w="165" data-h="32" data-locator_key="id" data-locator_value="com.spotify.music:id/toastie_container" draggable="true" style="left: 52.5px; top: 264.167px; width: 45.8333px; height: 8.88889px;"></div>

["次へ「アイコン」]
<div class="region" data-text="「次へ」アイコン" data-id="23" data-component="icon" data-item_count="" data-x="967" data-y="1483" data-w="83" data-h="83" data-locator_key="id" data-locator_value="com.spotify.music:id/toastie_container" draggable="true" style="left: 268.611px; top: 411.944px; width: 23.0556px; height: 23.0556px;"></div>

**Comment by NozomiIto** [comment]
Magic Podの不具合かもしれません。下記手順で情報を送付いただければ、後日詳しく調べてみます。

1. アサートで「Dail Mix1」が表示であることをチェックするなどして、テストをわざと失敗させる
2. 画面下「テスト実行結果」の #テスト番号のリンクからテスト結果画面に移動する。失敗テストの場合、「テスト失敗の理由を問い合わせる」ボタンがあるので、ボタンを押して詳しいテストの情報を送信

**Comment by yamatakau08** [comment]
ご指示のありました通り、メールにて送信しました。
可能であれば、こちらの issue board メインで、今後もやり取りさせて頂けると都合が良いです。

**Comment by NozomiIto** [comment]
問題を手元で修正しました。本日リリース予定です。

**Comment by NozomiIto** [comment]
修正をリリースしました。

- 画面要素のシステム情報がうまく取得できていないようでしたので、問題を修正しました。
- 問題が起きた画面のキャプチャは取得し直す必要があります。お手数ですがよろしくお願いします。
