### ISSUE TITLE
テスト結果が[要確認]の場合でも、テスト結果からUI登録を行いたい

### ISSUE THREAD

**Issue by yo-yoneyama** [Magic-Pod/japanese-issue-and-doc#493]
![スクリーンショット 2022-08-17 14 23 08](https://user-images.githubusercontent.com/10388255/185041210-bcde0d79-06c8-46c6-ae3e-c4eef1d0f2b7.png)

テスト結果からUI登録を行える機能が便利だが、テスト結果が失敗した場合しか導線が表示されない。
[要確認]でもロケータを調整したい場合（サジェストされたロケータ以外のものを利用したい)にUI登録が必要なため、失敗時と同様、テスト結果からUI登録が行えると助かります 🙇

**Comment by NozomiIto** [comment]
0.99.16で対応
