### ISSUE TITLE
テスト後にアプリがすぐ終了してしまうので、何が起こったかわからない時がある

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#50]
- 1秒くらいは終了前に待った方が良い
- バッチ実行の場合は1秒待ちがあると遅くなってしまうので、バッチ実行の際はまたない方が良い

**Comment by yamatakau08** [comment]
[行追加] → システム より、"アプリ終了"  のステップがあるので、
テスト終了後に、自動でテスト終了しなくても良いのではないでしょうか？

**Comment by NozomiIto** [comment]
"アプリ終了"は、主にテスト中でアプリを閉じて再度開くテスト用途に用意しております。

テスト終了後にアプリを閉じるかは、微妙な判断なのですが、以下の理由から当面は閉じることにしました。

- テスト終了後アプリを残した場合、次のテスト開始時にそれをクリアする必要があるのですが、前回のテストのプロセスはすでに終了しているので残ったアプリをうまく消せないリスクがある。

ただ、テスト作成中で色々試している時とかは、いちいち閉じられたくないこともあるはずで、そういう時に閉じないようにする機能はいずれ考えたいです。

**Comment by NozomiIto** [comment]
アプリを自動終了しなくても大丈夫そうですので、テスト終了後もアプリは終了せず残すことにしました。(バージョン0.18.0)
