### ISSUE TITLE
クラウドアップロードした任意のAppファイル(アーカイブ)をMagicPodのクラウド環境下でインストールできるようにする

### ISSUE THREAD

**Issue by gkzz** [Magic-Pod/japanese-issue-and-doc#516]
アプリのバージョンアップテストをするにあたり、あらかじめアップロードしたAppファイル(アーカイブ)のパスを指定できる環境（AWS EC2など）であれば、以下の記事で紹介されているように、「他のアプリを起動」コマンドでAppファイル(アーカイブ)のパスを指定してインストールすることができます。

しかし、MagicPodのクラウド環境下で、またクラウドアップロードしたAppファイルに対しては、記事で紹介されている方法を採用することはできないと思うので、要望としてお伝えさせていただきます。

アプリのバージョンアップテストがしたい – MagicPodヘルプセンター
https://support.magic-pod.com/hc/ja/articles/8941746639257-%E3%82%A2%E3%83%97%E3%83%AA%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E3%83%86%E3%82%B9%E3%83%88%E3%81%8C%E3%81%97%E3%81%9F%E3%81%84

**Comment by nkns165** [comment]
0.99.30で対応しました。
