### ISSUE TITLE
テストケースと共有ステップの検索で、番号も検索したい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#532]
- この番号のテストってどれ？がやりにくい
- 数字を入力したら番号、テストケース名、説明などを単に全部探す。
- `#123` など#つきで入力したら、その番号のものと、`#123` のような文字列が明示的に説明文内にあわられているものを返す。

**Comment by ReiAkimoto** [comment]
テスト一括実行設定にて指定されている「テストケース番号」がどのテストを指しているか確認したい。

**Comment by NozomiIto** [comment]
0.99.17で対応
