### ISSUE TITLE
プロジェクト間でテストケースの使いまわしがしたい

### ISSUE THREAD

**Issue by cct-yamashita** [Magic-Pod/japanese-issue-and-doc#541]
表題のとおりですが、プロジェクト間でテストケースの使いまわしができる機能の実装を検討いただけないでしょうか。

**Comment by ReiAkimoto** [comment]
@cct-yamashita 
お世話になっております。MagicPodカスタマーサクセスのAkimotoです。
ご起票いただきありがとうございます。
こちら「テストケースを他のプロジェクトに複製する」機能ですとご要望に沿っておりますでしょうか？
どうぞよろしくお願いいたします。

**Comment by cct-yamashita** [comment]
@ReiAkimoto 
お世話になっております。
はい、ご認識の通り「テストケースを他のプロジェクトに複製する」機能です。

**Comment by ReiAkimoto** [comment]
@cct-yamashita 
ご連絡ありがとうございます。
承知いたしました。
現在[プロジェクト内のテストケースを他のプロジェクトへ移したい #486](https://github.com/Magic-Pod/japanese-issue-and-doc/issues/486)にてその機能の作成中でございます。
issueの管理面で、もしかいたしますとこちらのissueへ統合する場合もございますが、ご容赦いただけますと幸いです。
どうぞよろしくお願いいたします。

**Comment by NozomiIto** [comment]
0.99.17で対応しました
