### ISSUE TITLE
WebAPIコールのURLに変数を代入できるようにしてほしい

### ISSUE THREAD

**Issue by cct-yamashita** [Magic-Pod/japanese-issue-and-doc#543]
例えば「MAILADDRESS」のような変数があった際、WebAPIコールのURLに「https://example.com/api?mail=${MAILADDRESS}」のような使い方ができるような機能の実装を検討いただけますでしょうか。

**Comment by mwakizaka** [comment]
@cct-yamashita 

ご要望ありがとうございます。
確認させていただいたのですが、WebAPIコールのURLに変数の使用は可能なようでした。
<img width="805" alt="Screen Shot 2022-11-28 at 12 10 22" src="https://user-images.githubusercontent.com/21286384/204183308-e579d700-98da-4a4a-a14d-2ca9824892e9.png">

お手数をおかけしますが、再度ご確認いただくことは可能でしょうか？もしそれでもWebAPIコールのURLに変数が使用できないようでしたら、一度テストケース結果画面からお問い合わせいただけますと幸いです。

**Comment by cct-yamashita** [comment]
@mwakizaka 
お世話になっております。
こちら確認してみたところ、WebAPIで変数を使うことができました。
エラーになっていた原因ですが、おそらく端末側のIMEの問題だったようです。
お手数おかけして申し訳ございません・・・

**Comment by mwakizaka** [comment]
ご確認ありがとうございます。無事動作していたようで安心しました。
またお気づきのことがあればお気軽にお知らせください！
