### ISSUE TITLE
組織で現在利用可能な端末の台数をAPIで取得したい

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/japanese-issue-and-doc#552]
- それによってテスト開始側で待つなどのプログラム作り込みができる
- 利用状況ページでGUIでも見れるといい

**Comment by nkns165** [comment]
APIでの取得については1.0.0で対応しました。
GUIは未対応です。

**Comment by nkns165** [comment]
GUIについても1.8.0で対応しました。組織の「利用状況」タブで確認が可能です。
ただし、現状「利用状況」タブは組織の更新権限を持っていないと表示できないため、権限管理については別途改善予定です。
