### ISSUE TITLE
利用状況に「クラウド端末数」も表示してほしい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#568]
テスト作成用 利用可能クラウド端末数
テスト実行用 利用可能クラウド端末数
が表示されているとよい

**Comment by nkns165** [comment]
1.8.0で対応しました。
ただし、現状「利用状況」タブは組織の更新権限を持っていないと表示できないため、権限管理については別途改善予定です。
