### ISSUE TITLE
UIの再アップロードや削除があった場合使用しているテストケースで警告を出して欲しい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#583]

**Comment by NozomiIto** [comment]
対応済み

![Screenshot 2023-11-14 at 12 23 35](https://github.com/Magic-Pod/japanese-issue-and-doc/assets/4276719/d4c93791-2f35-45f3-90f2-0a4819339455)

![Screenshot 2023-11-14 at 12 22 18](https://github.com/Magic-Pod/japanese-issue-and-doc/assets/4276719/2a1531c0-127c-4f58-a0c5-2e21b215b3ad)
