### ISSUE TITLE
テストケース内で使う値をAPI経由で書き換えたい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#584]

**Comment by rihokokabo** [comment]
MagicPod外の環境でテキストファイル内の値を一部変更しておき、それをアップロードしてテストケース内で使いたい

**Comment by NozomiIto** [comment]
- アップロードファイルに限らず外側から実行時に動的に制御したいという要望はあると思われるが、メンテナンス性の観点からこちらは共有変数を介するのが望ましい。
- アップロードファイルからも変数を呼べるようにするという課題は起票済み: https://github.com/Magic-Pod/japanese-issue-and-doc/issues/570 

以上からAPI経由でテスト内の値を書き換える機能は当面対応予定なし。
