### ISSUE TITLE
指定位置クリックコマンドに右クリックオプションがほしい

### ISSUE THREAD

**Issue by nakamurasato** [Magic-Pod/japanese-issue-and-doc#586]
右クリック時にメニューが表示されるWebサイトで、特定の要素がない場所またはある要素内の座標をクリックしたいが、現状では実現方法がない。
そのため、指定位置クリックコマンドに右クリックのオプションがほしい。

**Comment by kagaya-supsys** [comment]
@nakamurasato 
お世話になっております。以下、ご検討のほどよろしくお願い致します。

- 指定位置クリックコマンドに右クリックのオプションがほしい。
の件についてですが、いつ頃リリースされるのでしょうか？出来るだけ早くリリース希望です。
希望として、今週中、今月中には利用したいと存じます。よろしくお願い致します。

**Comment by nkns165** [comment]
お待たせいたしました。
0.99.30にて対応しました。
