### ISSUE TITLE
ベースURLを各テスト結果の画面で確認しやすいようにして欲しい

### ISSUE THREAD

**Issue by ReiAkimoto** [Magic-Pod/japanese-issue-and-doc#600]
①テストケースの「テスト結果」タブ画面
②プロジェクトの「テスト一括実行」タブ画面
③Slack通知

**Comment by NozomiIto** [comment]
https://github.com/Magic-Pod/japanese-issue-and-doc/issues/561 と同じ

**Comment by NozomiIto** [comment]
@ReiAkimoto #561  と同じなのでクローズします。
