### ISSUE TITLE
MagicPodAPIで実行時間も出力してほしい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#624]

**Comment by rihokokabo** [comment]
今は開始時刻と終了時刻で出るので、引き算を入れる必要がある。

**Comment by chaspy** [comment]
こちら補足します。
Get BatchRun API https://magic-pod.com/api/v1.0/doc/ で started_at と finished_at は帰ってくるのですが、duration_seconds のような実行時間が返ってくると楽です。（知りたいのはそちらなので）


<img width="564" alt="スクリーンショット 2023-07-14 20 12 54" src="https://github.com/Magic-Pod/japanese-issue-and-doc/assets/10370988/993c1185-e3a6-4296-ae31-3e4592828043">

こんな風に引き算しています。
https://github.com/chaspy/magicpod-datadog-action/blob/main/src/magicpod.ts#L171-L178

すればいいだけと言えばいい話なので、nits ですがフィードバックしておきます。
本日はお世話になりました。https://speakerdeck.com/chaspy/improved-e2e-testing-through-measurement

**Comment by nkns165** [comment]
MagicPod本体では0.99.39にて対応しました。
magicpod-api-clientについても一両日中に対応します。

**Comment by nkns165** [comment]
magicpod-api-client側も0.99.39.1で対応しました。
https://github.com/Magic-Pod/magicpod-api-client/releases/tag/0.99.39.1
