### ISSUE TITLE
変数つきのロケータを作成する際にChrome Developer Toolsなどを使わずに該当のUI要素をコピーや変数化したい

### ISSUE THREAD

**Issue by gkzz** [Magic-Pod/japanese-issue-and-doc#626]
以下のヘルプページを参考に、変数つきのロケータを作成することができます。

新しいロケータを追加する – MagicPodヘルプセンター
https://support.magic-pod.com/hc/ja/articles/4408903612825

しかし、MagicPod のテストケースの編集画面上では該当の UI 要素を探すことはできてもそれをコピーや変数化することがむずかしいです。
現状では、Chrome Developer Toolsなどを使って該当の UI 要素をコピーし、変数化するというやりかたをとるのが一般的かと思われます。

**Comment by NozomiIto** [comment]
現状の回避策としてはマウスで範囲選択して Ctrl + c (または Command + c)する方法もある。

![Screenshot 2023-11-16 at 8 02 01](https://github.com/Magic-Pod/japanese-issue-and-doc/assets/4276719/dabc9fef-3aad-4b72-8f7c-33f310c8aa90)

**Comment by nkns165** [comment]
1.7.0で対応しました。
・自動生成されたロケータのコピー
・手動で作成したロケータのコピーおよび編集
が可能になっています。
