### ISSUE TITLE
誰がテスト一括実行を実行したのか確認したい

### ISSUE THREAD

**Issue by mshimasan** [Magic-Pod/japanese-issue-and-doc#636]
MagicPodを組織全体に広く解放して、誰でも使えるようにしています。
API経由ではなく、画面からボタンを押して実行する運用にしていますが
成功していたら問題ないが、失敗がでていたときに誰が実行したのかわからず、コミュニケーションが取りづらいのが課題です。
テスト一括実行タブの一覧画面に、実行したユーザー名を表示して欲しいです。

**Comment by NozomiIto** [comment]
単体・一括実行とも

**Comment by NozomiIto** [comment]
ありがとうございます。
https://github.com/Magic-Pod/japanese-issue-and-doc/issues/603 に起票されているのでこちらはクローズさせていただければ幸いです。
