### ISSUE TITLE
テスト結果でも画面全体をキャプチャできる機能がほしい

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#638]

**Comment by NozomiIto** [comment]
@rihokokabo The same as https://github.com/Magic-Pod/japanese-issue-and-doc/issues/487 ?

**Comment by NozomiIto** [comment]
@rihokokabo Close since it is the same as https://github.com/Magic-Pod/japanese-issue-and-doc/issues/487
