### ISSUE TITLE
変数に保存した文字列が長い場合に内容が確認できない

### ISSUE THREAD

**Issue by rihokokabo** [Magic-Pod/japanese-issue-and-doc#669]
現在はログへの表示には200文字の制限があり、長いURLなどは正規表現で取得しても文字数が超えてしまうと表示されず確認できない

**Comment by nkns165** [comment]
1.8.0にて「ログ出力」コマンドを追加しました。
上限10000文字で任意の文字列を出力することができます。変数の値を表示したい場合は、下記のように指定できます。

<img width="430" alt="Screenshot 2024-02-26 at 8 56 27" src="https://github.com/Magic-Pod/japanese-issue-and-doc/assets/1135016/4ec36e33-2362-4aa5-b538-9e9ea5450239">
