### ISSUE TITLE
organizationsへのmember追加の際に、何も入力しなくても追加が出来てしまう

### ISSUE THREAD

**Issue by andysumi** [Magic-Pod/japanese-issue-and-doc#8]
未入力の際は、エラーにするなどの対応があると良いかと思います。
<img width="1000" alt="2017-04-19 13 25 01" src="https://cloud.githubusercontent.com/assets/8001405/25163228/abea896a-2503-11e7-9cac-f89eabbc598e.png">

**Comment by kojima** [comment]
Does not reproduce.
Please give me the reproduce instruction.

**Comment by NozomiIto** [comment]
修正しました。

https://github.com/Magic-Pod/japanese-issue-and-doc/blob/master/CHANGELOG.md#バージョン0422017423
